---
title: Lorenzo Beretta
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lorenzo2beretta@gmail.com
description: Lorenzo Beretta's personal web page
baseurl: ''
url: ''
github_username:
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
