---
title: Nicola Prezza
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: nicola.prezza@gmail.com
description: Nicola Prezza's personal web page
baseurl: ''
url: ''
github_username: nicolaprezza
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
