---
title: Lorenzo Beretta
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lorenzo2beretta@gmail.com
description: In TCS, it is all about the tricks.
baseurl: ''
url: ''
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
