---
title: Lorenzo Beretta
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: lorenzo2beretta@gmail.com
description: "Leave the world a little better than you found it."
baseurl: ''
url: ''
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
